import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {client} from "../lib/client"
import DefaultLayout from '../Layouts/layout'
import Card from '../components/Cards'
import {urlFor} from "../lib/client"
import img from "../images/husky.jpg"
import Image from "next/image"
import React from 'react'
import DogHome from '../components/DogHome/DogHome'
import Dogcarousel from '../components/DogCarousel/Dogcarousel'

export default function Home( {dogs}) {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Dogs Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DefaultLayout>

        <Dogcarousel />
        <DogHome />
         
      </DefaultLayout>

     
    </div>
  )
}

export const getServerSideProps = async () => {
  const query = '*[_type == "dogs"]';
  const dogs = await client.fetch(query)

  console.log("came here")
  // console.log(dogs)

  return{
    props:{
      dogs
    }
  }
}


// {
//   dogs?.map((dog)=> <>
//    <div className="card"  style={{width: "18rem"}}>
//    <img src={urlFor(dog.image)} className="card-img-top" alt="dog image" />
//  <div className="card-body">
//      <h5 className="card-title">{dog.breed}</h5>
//      <h6 className="card-subtitle mb-2 text-muted">{dog.breed}</h6>
//      <p className="card-text">{dog.details}</p>
//      <ul className="list-group list-group-flush">
//          <li className="list-group-item">Age: {dog.age}</li>
//          <li className="list-group-item">Gender: {dog.gender}</li>
//          <li className="list-group-item">Price: {dog.price}</li>
//      </ul>
//      <a onClick={()=> router.push(`dogs/${id}`)} className="btn btn-primary">Buy</a>
//  </div>
// </div>
 
//   </>)
//  }